# Generated by Django 4.2.1 on 2023-11-16 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subset',
            name='tipo',
        ),
        migrations.AddField(
            model_name='subset',
            name='type',
            field=models.CharField(choices=[('auto', 'Auto'), ('patch', 'Patch'), ('auto/patch', 'Auto/Patch'), ('base', 'Base')], default='base', max_length=255),
            preserve_default=False,
        ),
    ]
