# Generated by Django 4.2.1 on 2023-11-16 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_remove_subset_tipo_subset_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parallel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('numbered', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='set',
            old_name='league',
            new_name='leagues',
        ),
        migrations.AddField(
            model_name='subset',
            name='parallels',
            field=models.ManyToManyField(to='cards.parallel'),
        ),
    ]
