# Generated by Django 4.2.1 on 2023-11-16 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_parallel_rename_league_set_leagues_subset_parallels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subset',
            name='parallels',
        ),
        migrations.AddField(
            model_name='parallel',
            name='subset',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cards.subset'),
            preserve_default=False,
        ),
    ]
