# Generated by Django 4.2.1 on 2023-11-20 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_remove_subset_parallels_parallel_subset'),
    ]

    operations = [
        migrations.AddField(
            model_name='subset',
            name='basic',
            field=models.BooleanField(default=False),
        ),
    ]
